---
apiVersion: v1
kind: Service
metadata:
  name: dotnetcoreapi-service
  namespace: arc-core-api
  labels:
    name: dotnetcoreapi-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dotnetcoreapi
